### ISSUE TITLE
Implement Only User Middleware

### ISSUE THREAD

**Issue by AnudeepReddyBondugula** [AnudeepReddyBondugula/DigitalCertificateSystemBackend#27]
There are some routes which need to accessed only the users having the role **user**

Implement a middleware where it checks the request came from user role or not

**Note:** Check OnlyOrganizationMiddleware for reference

**Comment by AnudeepReddyBondugula** [comment]
@ssravan18 @vamshinallamothu  check it out

**Comment by vamshinallamothu** [comment]
assign me

**Comment by AnudeepReddyBondugula** [comment]
@vamshinallamothu have you resolved the issue?

**Comment by vamshinallamothu** [comment]
Not yet. I will do it now.
